services:
  rabbit:
    image: rabbitmq:management
    container_name: kolesa_rabbit
    networks: [ "kolesa" ]
    hostname: "rabbit"
    ports: [ "127.0.0.1:5672:5672", "127.0.0.1:15672:15672" ]
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - kolesa_rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:4.4
    container_name: kolesa_mongo
    networks: [ "kolesa" ]
    hostname: "mongo"
    ports: [ "127.0.0.1:27017:27017" ]
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: pass
      MONGODB_INITDB_DATABASE: kolesa
    volumes: [ "kolesa_mongo:/data/db" ]
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "127.0.0.1:27017/test", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    container_name: kolesa_minio
    networks: [ "kolesa" ]
    hostname: "minio"
    ports: [ "127.0.0.1:9000:9000", "127.0.0.1:9001:9001" ]
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: pass-pass
    volumes: [ "minio_data:/data" ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kolesa_rabbitmq:
    name: kolesa_rabbitmq
  kolesa_mongo:
    name: kolesa_mongo
  minio_data:
    name: minio_data

networks:
  kolesa:
    name: kolesa